### PR TITLE
Add Methods and Specs to calendarView.js

### LINKED ISSUE #9: Write method names and specifications for calendarView
Write out all of the method titles that we expect to need inside the calendarView.js file and write specifications for each method.

### PR DESCRIPTION
**Pull request by raezedge**
## Closes #9
Added methods and specs:
- highlightDay()
- expandDay()

### CODE REVIEW

**Comment by raezedge** [comment]
Removed methods that will be put into task.js, more detail

**Comment by ebellino** [comment]
looks good, but is that proper commenting O.o?

**Review by ebellino — DISMISSED** [review]
Evan likey

**Review by StephenRhoades — DISMISSED** [review]
Each of the methods that are already there should also have javadocs. What you have for these two methods looks good though.

**Review by calpyo2454 — APPROVED** [review]

**Review by ebellino — APPROVED** [review]

**Pull request merged**
